=== lakestephen/ringingmaster_cpp/Supporting Projects/ModelGenerator/ModelGenerator/input/model.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT columnName (#PCDATA)>
<!ELEMENT variableName (#PCDATA)>
<!ELEMENT infoName (#PCDATA)>
<!ELEMENT customType (#PCDATA)>
<!ELEMENT enumName (#PCDATA)>
<!ELEMENT field (variableName, customType?, enumName?, infoName?)>
<!ATTLIST field
	type (BOOL | int | long | double | CString | COleDateTime | enum | custom | Info) #REQUIRED
>
<!ELEMENT model (field+)>
<!ATTLIST model
	classname NMTOKEN #REQUIRED
>

=== lakestephen/ringingmaster_cpp/Supporting Projects/ModelGenerator/ModelGenerator/input/grab.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE model SYSTEM "model.dtd">

<model classname="Grab">
  <field type="COleDateTime">
    <variableName>GrabDate</variableName>
  </field>
  <field type="enum">
    <variableName>BellsGo</variableName>
    <enumName>BellsGo</enumName>
  </field>
  <field type="enum">
    <variableName>BellsSound</variableName>
    <enumName>BellsSound</enumName>
  </field>
  <field type="CString">
    <variableName>Comments</variableName>
  </field>
  <field type="Info">
    <variableName>ParentTower</variableName>
    <infoName>Tower</infoName>
  </field>

</model>

=== lakestephen/ringingmaster_cpp/Supporting Projects/ModelGenerator/ModelGenerator/input/tower.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE model SYSTEM "model.dtd">

<model classname="Tower">
  <field type="custom">
    <variableName>GridRef</variableName>
    <customType>MapGridRef</customType>
  </field>
  <field type="CString">
    <variableName>County</variableName>
  </field>
  <field type="CString">
    <variableName>Name</variableName>
  </field>
  <field type="CString">
    <variableName>Dedication</variableName>
  </field>
  <field type="CString">
    <variableName>PostCode</variableName>
  </field>
  <field type="BOOL">
    <variableName>GroundFloor</variableName>
  </field>
  <field type="int">
    <variableName>Number</variableName>
  </field>
  <field type="double">
    <variableName>Weight</variableName>
  </field>
  <field type="BOOL">
    <variableName>Approx</variableName>
  </field>
  <field type="enum">
    <variableName>Note</variableName>
    <enumName>Note</enumName>
  </field>
  <field type="enum">
    <variableName>Night</variableName>
    <enumName>Night</enumName>
  </field>
  <field type="BOOL">
    <variableName>Unringable</variableName>
  </field>
  <field type="CString">
    <variableName>WebPage</variableName>
  </field>
  <field type="CString">
    <variableName>Country</variableName>
  </field>
</model>
